import React from "react";
// import { useState } from "react";
import Image from "next/image";
import Button from "react-bootstrap/Button";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import styles from "./Login.module.css";
import Card from "react-bootstrap/Card";
// import Spinner from "react-bootstrap/Spinner";
// import { useRouter } from "next/router";
import Head from "next/head";
import logo from "@/../public/assets/telkomsel.png";
import Form from "react-bootstrap/Form";
const LoginPage = () => {
    // const { push } = useRouter();
    // const [loading, setLoading] = useState(false);
  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/telkomsel.svg" />
      </Head>
      <Container fluid className={styles.loginPage}>
        <Card className={styles.cardBackground}>
          <Row className={styles.customRow}>
            <Card.Body>
              <Row>
                <Col className={styles.colorRow}>
                  <Image src={logo} alt="logo" className={styles.logo} />
                </Col>
              </Row>
              <Row>
                <Card.Title style={{ fontWeight: "bold" }}>
                  Hello Friends! 👋👋
                </Card.Title>
              </Row>
              <Card.Text className="text-muted" style={{ fontSize: "14px" }}>
                Log in to get access data and dashboard Telkomsel Indonesia!
              </Card.Text>
              <Form>
                <Form.Group className="mb-3" controlId="exampleForm.ControlInput1">
                  <Form.Label style={{ fontWeight: "bold" }}>
                    Email address
                  </Form.Label>
                  <Form.Control type="email" placeholder="Enter email" />
                  <Form.Text className="text-muted">
                    Please login with Telkomsel email employee (...@telkomsel.co.id)
                  </Form.Text>
                </Form.Group>
                <Form.Group className="mb-3" controlId="formBasicPassword">
                  <Form.Label style={{ fontWeight: "bold" }}>
                    Password
                  </Form.Label>
                  <Form.Control type="password" placeholder="Password" />
                </Form.Group>
                <Form.Group className="mb-3" controlId="formBasicCheckbox">
                  <Form.Check type="checkbox" label="Remember Me" />
                </Form.Group>
              </Form>
              <div className="d-grid gap-2">
                <Button variant="danger" size="lg">
                  Login
                </Button>
              </div>
              <div className="d-flex justify-content-center align-items-center mt-2 mb-2">
                <Card.Text style={{ fontSize: "14px" }}>
                Don&apos;t have an account?
                </Card.Text>
              </div>
              <div className="d-grid gap-2">
                <Button variant="outline-dark" size="lg">
                  Register Account
                </Button>
              </div>
            </Card.Body>
          </Row>
        </Card>
      </Container>
    </>
  );
};
export default LoginPage;
