import LeafletMap from "@/components/Map/SiteMap";
import Head from "next/head";

export default function MapPage() {
  return (
    <>
      <Head>
        <title>BTS Map</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/telkomsel.svg" />
      </Head>
      <LeafletMap />
    </>
  );
}
