import LeafletMap from "@/components/Map/SiteMap";
import InfoMap from "@/components/Offcanvas/SiteMap";
import { useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";

export default function MapPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [show, setShow] = useState(false);
  const [chartData, setChartData] = useState<
    {
      trx_date: string;
      total_rev: number;
      total_payload: number;
      total_traffic: number;
    }[]
  >([]);

  const handleShow = async (site_id: string) => {
    setLoading(true);
    try {
      const response = await fetch(`/api/siteperformance/${site_id}`);
      if (response.ok) {
        const data = await response.json();
        setChartData(data.performance || []); // Pastikan key `performance` di API mengandung data chart
      } else {
        console.error("Failed to fetch site performance data");
        setChartData([]);
      }
      setShow(true);
      router.push(`/map/sitemap?${site_id}`);
    } catch (err) {
      console.error("Error fetching data:", err);
      setChartData([]);
    } finally {
      setLoading(false);
    }
  };

  const handleClose = () => {
    setShow(false);
    setChartData([]);
    router.push("/map/sitemap");
  };

  return (
    <>
      <Head>
        <title>Map Site Level</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/telkomsel.svg" />
      </Head>
      <LeafletMap handleShow={handleShow} />
      <InfoMap
        show={show}
        chartData={chartData}
        handleClose={handleClose}
        loading={loading}
      />
    </>
  );
}
