import Head from "next/head";
import Navbar from "@/components/Navbar";

export default function HomePage() {
    return (
        <>
            <Head>
                <title>Simple Nextjs App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/telkomsel.svg" />
            </Head>
            <Navbar />
        </>
    );
}
