import Head from "next/head";
import Navbar from "@/components/Navbar";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import style from "./HomePage.module.css"
import CardMap from "@/components/Cards/Map";

export default function HomePage() {
    return (
        <>
            <Head>
                <title>Main Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/telkomsel.svg" />
            </Head>
            <Navbar />
            <Container fluid>
                <Row className={style.customContainer}>
                    <CardMap/>
                </Row>
                <Row className={style.customContainer}>
                    aldknadnk
                </Row>
            </Container>
        </>
    );
}
