import React, { useState } from "react";
import Image from "next/image";
import Button from "react-bootstrap/Button";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import styles from "./LandingPage.module.css";
import Card from "react-bootstrap/Card";
import Spinner from "react-bootstrap/Spinner";
import telkomsel from "@/../public/assets/telkomsel.png";
import { useRouter } from "next/router";
import Head from "next/head";

const LandingPage = () => {
  const { push } = useRouter();
  const [loading, setLoading] = useState(false);

  const handleClick = () => {
    setLoading(true); // Aktifkan spinner
    setTimeout(() => {
      setLoading(false); // Matikan spinner (opsional jika navigasi cepat)
      push("/auth/login"); // Navigasi ke halaman login
    }, 2000); // Simulasi loading 2 detik
  };

  return (
    <>
      <Head>
        <title>Network Analysis Report | Telkomsel Jawa Bali</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/telkomsel.svg" />
      </Head>
      <Container fluid className={styles.landingPage}>
        <Row className={styles.cardBackground}>
          <Card className="text-center" style={{ border: "none" }}>
            <Card.Body>
              <Row className="align-items-center">
                <Col xs={12} md={4} className="text-center mb-3 mb-md-0">
                  <Image
                    src={telkomsel}
                    alt="telkomsel"
                    width={125}
                    height={72.5}
                    className="justify-content-center align-items-center d-inline-block"
                  />
                </Col>
                <Col xs={12} md={8} className={styles.customCol}>
                  <Card.Title className={styles.title}>
                    Network Analysis Dashboard
                  </Card.Title>
                </Col>
              </Row>
              <Card.Text>
                Welcome to Network Analysis Dashboard Telkomsel Jawa Bali. This
                dashboard is designed to provide a comprehensive overview of
                Telkomsel&apos;s network performance in Jawa Bali.
              </Card.Text>
              <Card.Text>
                <strong>🚀 Start Exploring 🚀</strong>
              </Card.Text>
              <Button variant="danger" onClick={handleClick} disabled={loading}>
                {loading ? (
                  <>
                    <Spinner
                      as="span"
                      animation="border"
                      size="sm"
                      role="status"
                      aria-hidden="true"
                    />
                    {" Loading..."}
                  </>
                ) : (
                  "Get Started"
                )}
              </Button>
            </Card.Body>
          </Card>
        </Row>
      </Container>
    </>
  );
};

export default LandingPage;
